### ISSUE TITLE
Analyzer assembly loading errors

### ISSUE THREAD

**Issue by sapsari** [merryyellow/Unity-Code-Assist#20]
Thousands of warnings created by below when CodeAnalysis is run on solution wide at UCA project

Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Meryel.UnityCodeAssist.Analyzers.ReciprocalAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.'.
Exception occurred with following context:
Compilation: UnityCodeAssistAdornmentColor
SyntaxTree: D:\Develop\UnityCodeAssist\src\UnityCodeAssist\AdornmentColor\ColorSpace.cs
SyntaxNode: NamedColors.Length / 2 [BinaryExpressionSyntax]@[5486..5508) (71,22)-(71,44)

System.IO.FileNotFoundException: Could not load file or assembly 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.
File name: 'Serilog, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'
   at Meryel.UnityCodeAssist.Analyzers.ReciprocalAnalyzer.AnalyzeBinaryExpression(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__55`1.<ExecuteSyntaxNodeAction>b__55_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: UCA1007	AdornmentColor	D:\Develop\UnityCodeAssist\src\UnityCodeAssist\AdornmentColor\AdornmentColor.csproj	1	Active

**Comment by sapsari** [comment]
see also
https://community.sonarsource.com/t/ad0001-errors-system-io-filenotfoundexception-could-not-load-file-or-assembly-sonaranalyzer-cfg/71341/13
https://github.com/SonarSource/sonarlint-visualstudio/issues/3322
https://github.com/search?q=%22run+code+analysis+in+a+separate+process%22&type=issues
