### ISSUE TITLE
Meryel.UnityCodeAssist.ProjectData.LitJson.JsonException   D:\Develop\github\litjson\src\LitJson\JsonMapper.cs in void JsonMapper.WriteValue(object obj, JsonWriter writer, bool writer_is_private, int depth)  New Level: Error Max allowed object depth reached while trying to export from type

### ISSUE THREAD

**Issue by sapsari** [merryyellow/Unity-Code-Assist#28]
17:03:36.100 [VS] [ERR] [1] Unhandled exception at IVsRunningDocTableEvents.OnBeforeDocumentWindowShowAsync
Meryel.UnityCodeAssist.ProjectData.LitJson.JsonException: Max allowed object depth reached while trying to export from type System.Boolean
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 725
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Object obj, JsonWriter writer, Boolean writer_is_private, Int32 depth) in D:\Develop\github\litjson\src\LitJson\JsonMapper.cs:line 858
   at Meryel.UnityCodeAssist.ProjectData.LitJson.JsonMapper.WriteValue(Obj...

D:\Develop\github\litjson\src\LitJson\JsonMapper.cs in void JsonMapper.WriteValue(object obj, JsonWriter writer, bool writer_is_private, int depth) at line 725:17
In App

Assembly:
Meryel.UnityCodeAssist.ProjectData
Version:
1.3.3.0
D:\Develop\github\litjson\src\LitJson\JsonMapper.cs in void JsonMapper.WriteValue(object obj, JsonWriter writer, bool writer_is_private, int depth) x 101 at line 858:46
In App

D:\Develop\github\litjson\src\LitJson\JsonMapper.cs in string JsonMapper.ToJson(object obj) at line 898:17
In App

void LogEvent.RenderMessage2(TextWriter writer)+RenderMessageAux(TextWriter writer)
In App

void LogEvent.RenderMessage2(TextWriter writer)
In App

string LogEvent.RenderForFileLogger((string messageTemplate, object[] messageArguments) state, Exception ex)
In App

void FileLogger.Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)
In App

void FileSink.Emit(LogEvent logEvent)
In App

void LoggerManager.Log(LogEventLevel level, Exception ex, string messageTemplate, params object[] messageArguments)
In App

D:\Develop\UnityCodeAssist\src\UnityCodeAssist\VSIXLibrary\UnityClassWalker.cs in ClassKind UnityClassWalker.VisitClassDeclarationAux(ClassDeclarationSyntax node) at line 207:21
In App

D:\Develop\UnityCodeAssist\src\UnityCodeAssist\VSIXLibrary\UnityClassWalker.cs in void UnityClassWalker.VisitClassDeclaration(ClassDeclarationSyntax node) at line 130:13
In App

CSharpSyntaxWalker.cs in void CSharpSyntaxWalker.Visit(SyntaxNode node) at line 31

CSharpSyntaxWalker.cs in void CSharpSyntaxWalker.DefaultVisit(SyntaxNode node) at line 51

CSharpSyntaxWalker.cs in void CSharpSyntaxWalker.Visit(SyntaxNode node) at line 31

D:\Develop\UnityCodeAssist\src\UnityCodeAssist\VSIXLibrary\DocumentValidator.cs in async Task<(string[] result, string verboseText)> DocumentValidator.GetIsUnityClassAsync(bool isVerbose) at line 80:17
In App

D:\Develop\UnityCodeAssist\src\UnityCodeAssist\VSIX\VSDocumentEvents.cs in async Task<string[]> VsDocument.GetDeclaredUnityClassesAsync() at line 382:13
In App

D:\Develop\UnityCodeAssist\src\UnityCodeAssist\VSIX\VSDocumentEvents.cs in async Task VsDocumentEvents.OnBeforeDocumentWindowShowAsync(uint docCookie) at line 285:21
In App

**Comment by sapsari** [comment]
switched back to newtonsoft.json for to fix this (along with another litjson issue)
